### ISSUE TITLE
Use Dokku rather than Heroku

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpathology-web#3]
We currently use Heroku. 

As long as the website is only copy, we can run it as a free dyno through Cloudflare.

Thereafter, it is hard to estimate the level of dyno we would need in production. It could be anywhere from $7 to $250 per month.

In terms of postgres we would probably want the [Standard Tier](https://devcenter.heroku.com/articles/heroku-postgres-plans#standard-tier) for better memory profiles and no row-count limits. I would guess the first level would be sufficient at $50/month, but it looks like OpenPrescribing would probably require about $750/month to run in its current incarnation (for example).

In total we could expect Heroku-based hosting to cost somewhere in the region of $100/month initially, going up to a maximum of $1000/month longer term.

The benefits of using Heroku are:

* Outsourced sysadmin
  * Availability management
  * SLAs 
  * System patching
  * Database rollback

The alternative route is self-hosting using the same (or similar) APIs to Heroku. The obvious answer is Dokku, which would support apps with no changes, but without horizontal scaling, and without Heroku tooling around deployment, logging etc.  This has an upgrade path to [flynn](https://flynn.io) which is an open source enterprisey solution but seems very complex.

Dokku looks pretty safe to use and should meet our requirements very well, and is quite simple.  We would want to sort out logging, as Dokku currently relies on the output of docker log, which means the log outputs are ephemeral. The current recommended solution to this is a dokku plugin which uses a docker log router that can send stuff to syslog.

**Comment by sebbacon** [comment]
I've done this for now - but not sure the logspout stuff is working, so leaving this ticket open while I deal with other stuff.

To set up logspout:

* Installed [per instructions](https://github.com/michaelshobbs/dokku-logspout)
* Set up rsyslogd to listen to UDP:
    ```
    module(load="imudp")
    input(type="imudp" port="514")
    ```
* Blocked this for non-docker hosts in `ufw` with `ufw allow to 0.0.0.0 port 514 proto udp  from 172.18.0.0/16`
* Set the following in `/home/dokku/.logspout/OPTS`:
    ```
    export DOKKU_LOGSPOUT_SYSLOG_SERVER=syslog://dokku.ebmdatalab.net:514
    export DOKKU_LOGSPOUT_PORT=8080
    ```

I'm not sure if logs are getting through or not; nginx logs are going to the host nginx logs anyway

**Comment by josegonzalez** [comment]
We have an under-development [kubernetes plugin](https://github.com/dokku/dokku-scheduler-kubernetes) that works fairly well, and may be of use to you.
